# Generated by Django 3.2.15 on 2023-04-18 09:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('field_definition', django.contrib.postgres.fields.jsonb.JSONField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_data', django.contrib.postgres.fields.jsonb.JSONField(db_index=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mushroomspot',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.CreateModel(
            name='ProjectDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('entry_definitions', models.ManyToManyField(to='mushrooms.EntryDefinition')),
            ],
        ),
    ]
