# Generated by Django 3.2.15 on 2023-04-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0002_auto_20230418_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrydefinition',
            name='field_definition',
            field=models.JSONField(db_index=True),
        ),
        migrations.AlterField(
            model_name='userentry',
            name='field_data',
            field=models.JSONField(db_index=True),
        ),
    ]
