# Generated by Django 3.2.15 on 2023-04-18 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0003_auto_20230418_0936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MushroomSpot',
        ),
    ]
