# Generated by Django 3.2.15 on 2023-04-18 09:54

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0004_delete_mushroomspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentry',
            name='geometry',
            field=djgeojson.fields.PolygonField(default=123),
            preserve_default=False,
        ),
    ]
