# Generated by Django 3.2.15 on 2023-10-10 11:23

from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntryDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('field_definition', models.JSONField(db_index=True)),
            ],
            options={
                'unique_together': {('name', 'field_definition')},
            },
        ),
        migrations.CreateModel(
            name='LocationEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', djgeojson.fields.PointField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('demographic_entry_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_demographics', to='webgis.entrydefinition')),
                ('survey_entry_definitions', models.ManyToManyField(related_name='project_surveys', to='webgis.EntryDefinition')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_data', models.JSONField(db_index=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgis.entrydefinition')),
                ('location_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgis.locationentry')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgis.projectdefinition', to_field='url')),
            ],
        ),
        migrations.AddField(
            model_name='locationentry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgis.projectdefinition', to_field='url'),
        ),
        migrations.CreateModel(
            name='DemographicEntry',
            fields=[
                ('survey_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webgis.surveyentry')),
                ('field_data', models.JSONField(db_index=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgis.entrydefinition')),
            ],
        ),
    ]
