# Generated by Django 3.2.15 on 2023-12-30 22:47

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationentry',
            name='geom',
            field=djgeojson.fields.GeoJSONField(),
        ),
    ]
