# Generated by Django 3.2.15 on 2023-04-18 10:10

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webgis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('field_definition', models.JSONField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_data', models.JSONField(db_index=True)),
                ('geom', djgeojson.fields.PolygonField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('entry_definitions', models.ManyToManyField(to='webgis.EntryDefinition')),
            ],
        ),
    ]
