# Generated by Django 3.2.15 on 2025-03-10 09:25

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdefinition',
            name='bounds',
            field=djgeojson.fields.MultiPointField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdefinition',
            name='limit_to_bounds',
            field=models.BooleanField(default=False),
        ),
    ]
