# Generated by Django 3.2.15 on 2023-10-10 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdefinition',
            name='demographic_entry_definitions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_demographics', to='webgis.entrydefinition'),
        ),
    ]
