# Generated by Django 3.2.15 on 2023-10-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0002_alter_projectdefinition_demographic_entry_definitions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdefinition',
            old_name='demographic_entry_definitions',
            new_name='demographic_entry_definition',
        ),
    ]
