# Generated by Django 5.2.4 on 2025-07-29 09:43

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0002_auto_20250310_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrydefinition',
            name='field_definition',
            field=django_jsonform.models.fields.JSONField(db_index=True),
        ),
    ]
