# Generated by Django 3.2.15 on 2023-04-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0002_entrydefinition_projectdefinition_userentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdefinition',
            name='url',
            field=models.CharField(default='biopv', max_length=16),
            preserve_default=False,
        ),
    ]
