# Generated by Django 3.2.15 on 2023-04-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0003_projectdefinition_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdefinition',
            name='url',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
