# Generated by Django 5.2.4 on 2025-07-31 06:49

from django.db import migrations

def update_field_definition_data(apps, schema_editor):
    """
    Updates the `field_definition` JSON data to an array format necessary for the
    django-jsonform schema. 
    
    E.g.
    {
        "An diesem Ort kann ich mir Synergies zwischen folgenden Punkten vorstellen": {
            "type": "Checkbox",
            "description": "Wählen Sie alle zutreffenden Felder aus.",
            "params": {
                "values": [
                    "PV Anlagen",
                    "Artenvielfalt",
                    "Freizeitnutzung",
                    "Naturschutz"
                ]
            }
        },
        ...
    }
    
    will become
    
    [
        {
            "question": "An diesem Ort kann ich mir Synergies zwischen folgenden Punkten vorstellen"
            "type":  "Checkbox",
            "description":  "Wählen Sie alle zutreffenden Felder aus.",
            "params": {
                "values": [
                    "PV Anlagen",
                    "Artenvielfalt",
                    "Freizeitnutzung",
                    "Naturschutz"
                ]
            },
            ...
        }
    ]
    """
    EntryDefinition = apps.get_model('webgis', 'EntryDefinition')
    
    for entry_definition in EntryDefinition.objects.all():
        new_field_def = []
        for key, other_fields in entry_definition.field_definition.items():
            # Save fields into a new dict
            new_fields: dict = {}
            # The first key is what used to be the question (see above)
            new_fields["question"] = key
            # Copy the remaining fields
            for key, item in other_fields.items():
                new_fields[key] = item
            
            # Append to the new structure of EntryDefinition.field_definition
            new_field_def.append(new_fields)

        entry_definition.field_definition = new_field_def
        entry_definition.save()
            

class Migration(migrations.Migration):
    dependencies = [
        ('webgis', '0003_alter_entrydefinition_field_definition'),
    ]

    operations = [
        migrations.RunPython(update_field_definition_data)
    ]
