# Generated by Django 3.2.15 on 2023-10-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0003_rename_demographic_entry_definitions_projectdefinition_demographic_entry_definition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserEntry',
            new_name='SurveyEntry',
        ),
    ]
