# Generated by Django 3.2.15 on 2023-10-10 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0004_rename_userentry_surveyentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemographicEntry',
            fields=[
                ('survey_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webgis.surveyentry')),
                ('field_data', models.JSONField(db_index=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgis.entrydefinition')),
            ],
        ),
    ]
