# Generated by Django 3.2.15 on 2023-04-19 12:14

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0004_alter_projectdefinition_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentry',
            name='geom',
            field=djgeojson.fields.PointField(),
        ),
    ]
