# Generated by Django 5.2.4 on 2025-07-31 09:31

from django.db import migrations

def update_field_definition_data(apps, schema_editor):
    """
    The previous migration (004) did not respect the necessary "kind" field in under the params dict. We will copy this according to the type.
    This field is necessary because otherwise two definitions that are the same (e.g. comment and multiline) will break django-json and the dropdown
    menu will not work.
    
    ...
    "question": "An diesem Ort kann ich mir Synergies zwischen folgenden Punkten vorstellen"
    "type":  "Checkbox",
    "description":  "Wählen Sie alle zutreffenden Felder aus.",
    "params": {
        "values": [
            "PV Anlagen",
            "Artenvielfalt",
            "Freizeitnutzung",
            "Naturschutz"
        ]
    }
    ...
            
    will become
    
    ...
    "question": "An diesem Ort kann ich mir Synergies zwischen folgenden Punkten vorstellen"
    "type":  "Checkbox",
    "description":  "Wählen Sie alle zutreffenden Felder aus.",
    "params": {
        "kind": "Checkbox",
        "values": [
            "PV Anlagen",
            "Artenvielfalt",
            "Freizeitnutzung",
            "Naturschutz"
        ]
    }
    ...
    """
    EntryDefinition = apps.get_model('webgis', 'EntryDefinition')
    
    for entry_definition in EntryDefinition.objects.all():
        for question_definition in entry_definition.field_definition:
            # Copy the type over to the params field
            question_definition["params"]["kind"] = question_definition["type"]

        entry_definition.save()
            

class Migration(migrations.Migration):
    dependencies = [
        ('webgis', '0004_update_json_schema_data'),
    ]

    operations = [
        migrations.RunPython(update_field_definition_data)
    ]