# Generated by Django 3.2.15 on 2023-04-19 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0007_userentry_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgis.projectdefinition', to_field='url'),
        ),
    ]
