# Generated by Django 3.2.15 on 2023-10-09 18:32

from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0009_alter_entrydefinition_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userentry',
            name='geom',
        ),
        migrations.CreateModel(
            name='LocationEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', djgeojson.fields.PointField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgis.projectdefinition', to_field='url')),
            ],
        ),
        migrations.AddField(
            model_name='userentry',
            name='location_entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webgis.locationentry'),
            preserve_default=False,
        ),
    ]
